nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:[0-9]+']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
        expose_headers: ['Access-Control-Allow-Origin']
        max_age: 3600
    paths: 
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']

